export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  WAITING_ROOM: '/waiting-room',
  PATIENTS: '/patients',
  PATIENT_DETAILS: '/patients/:nationalId',
  QUEUE: '/queue',
  APPOINTMENTS: '/appointments',
  APPOINTMENT_SCHEDULE: '/appointments/schedule',
  CLINIC_HOURS: '/clinic-hours',
  VISITS: '/visits',
  VISIT_NEW: '/visits/new',
  VISIT_DETAILS: '/visits/:visitId',
  PRESCRIPTIONS: '/prescriptions',
  PRESCRIPTION_NEW: '/prescriptions/new',
  PRESCRIPTION_DETAILS: '/prescriptions/:prescriptionId',
  PRESCRIPTION_EDIT: '/prescriptions/:prescriptionId/edit',
};
